version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./input_files:/app/input_files
      - ./outputs:/app/outputs
    env_file:
      - .env
    restart: unless-stopped 